spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wifinderDB
    username: WIFINDER
    password: wifound

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update