spring:
  application:
    name: Wifinder

  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://wifinderdb.cqfumk5mvaun.eu-west-3.rds.amazonaws.com:5432/aws_wifinder_db
    url: jdbc:postgresql://localhost:5432/wifinderDB
#    username: wifinder_user
    username: WIFINDER
#    password: wifound_aws
    password: wifound

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
        jdbc.lob.non_contextual_creation: true

    database: postgresql



server:
  port: 8080
#logging:
#  level:
#    insaif : debug
