spring:
  application:
    name: Wifinder

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wifinderDB
    username: WIFINDER
    password: wifound

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc.lob.non_contextual_creation: true

    database: postgresql



server:
  port: 8443

  ssl:
    key-store-type: JKS
    key-store: ssl-server.jks
    key-store-password: wifound
    key-alias: wifinder_dev_sslserver
    key-password: wifound
    key-store-provider: SUN

#logging:
#  level:
#    insaif : debug
